### ISSUE TITLE
긴급HELP!긴급HELP!긴급HELP!긴급HELP!긴급HELP!

### ISSUE THREAD

**Issue by DilettanteKOR** [2021-SMHRD-KDT-AI-1/Cold-Brew-Latte#27]
html , visual studio에서 오류가없는 코드가 jsp 파일로 불러왔을 때 태그가 닫혀있지 않다고 오류가뜹니다...

에러코드입니다... 확인부탁드립니다.
Multiple annotations found at this line:

**Comment by Koth100** [comment]
자세한건 확인해봐야 알겠지만, 해당 프로젝트가 톰캣을 제대로 못잡고 있을 확률이 있습니다.
왼쪽 프로젝트뷰어에서 해당 프로젝트 우클릭 - Build path - configure Build Path -Libraries 탭
으로 가셔서 모든 라이브러리가 정상으로 설정되어있는지 확인해보셔야 할거 같습니다.
